---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kcm
  namespace: {{ .kcm.namespace }}
spec:
  project: default
  source:
    repoURL: {{ .kcm.repository }}
    targetRevision: {{ .kcm.version }}
    chart: {{ .kcm.chart }}
  destination:
    name: "in-cluster"
    namespace: {{ .kcm.namespace }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
